# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 粉笔灰杂谈
email: siglea@sina.com
description:  # this means to ignore newlines until "baseurl:"
  关于产品、技术、商业的一些见解，顺便记录一下自己的生活感悟和读书笔记。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.fenbihui.cn" # the base hostname & protocol for your site
github_username:  siglea

# Gems settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo
  - jekyll-archives

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5

#theme: jekyll-theme-cayman